### ISSUE TITLE
DNS

### ISSUE THREAD

**Issue by technomancy** [technomancy/diginet#3]
Dealing in terms of addresses for everything is kinda tedious.

**Comment by technomancy** [comment]
One idea was to create a tool item that you can point at nodes to assign them DNS entries.

Do we need to set up permissions where you can only overwrite entries if you were the one who placed them?

**Comment by asl97** [comment]
maybe a node as the dns server as well using a Scrollable itemlist formspec or formspec with pages like unified inventory

people can input the pos and name using both the dns server interface as well as the tool
and they can view all the entries using the server.

**Comment by technomancy** [comment]
@asl97 Nice idea! I've pushed out an implementation that does this, but because it's late and because formspecs are a PITA I've hard-coded the form to only supporting 4 entries for now, but it seems to get the job done.
